name: shell-ci

on:
  push:
    branches: [main]
    paths:
      - "bin/**"
      - "benchmarks/**"
      - "docs/**"
      - "Makefile"
  pull_request:
    paths:
      - "bin/**"
      - "benchmarks/**"
      - "docs/**"
      - "Makefile"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make lint
